apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.scheduler.schedulerName }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: scheduler
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: scheduler
    spec:
    {{- if .Values.scheduler.serviceAccount }}
      serviceAccount: {{ .Values.scheduler.serviceAccount }}
    {{- end }}
      containers:
      - name: {{ .Values.scheduler.schedulerName }}
        image: {{ .Values.operatorImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
        command:
          - /usr/local/bin/tidb-scheduler
          - -v={{ .Values.scheduler.logLevel }}
          - -port=10262
        {{- if .Values.scheduler.features }}
          - -features={{ join "," .Values.scheduler.features }}
        {{- end }}
      {{- if and (ne .Values.timezone "UTC") (ne .Values.timezone "") }}
        env:
        - name: TZ
          value: {{ .Values.timezone | default "UTC" }}
      {{- end }}
      - name: kube-scheduler
        image: {{ required "scheduler.kubeSchedulerImageName is required" .Values.scheduler.kubeSchedulerImageName }}:{{ .Values.scheduler.kubeSchedulerImageTag | default (split "-" .Capabilities.KubeVersion.GitVersion)._0 }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
        command:
        - kube-scheduler
        - --port=10261
        - --leader-elect=true
        - --lock-object-name={{ .Values.scheduler.schedulerName }}
        - --lock-object-namespace={{ .Release.Namespace }}
        - --scheduler-name={{ .Values.scheduler.schedulerName }}
        - --v={{ .Values.scheduler.logLevel }}
        - --policy-configmap={{ .Values.scheduler.schedulerName }}-policy
        - --policy-configmap-namespace={{ .Release.Namespace }}
      {{- if and (ne .Values.timezone "UTC") (ne .Values.timezone "") }}
        env:
        - name: TZ
          value: {{ .Values.timezone | default "UTC" }}
      {{- end }}
