{{- if .Values.binlog.drainer.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cluster.name" . }}-drainer
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: drainer
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  clusterIP: None
  ports:
  - name: drainer
    port: 8249
  selector:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: drainer
{{- end }}
