{{- if .Values.monitor.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.clusterName }}-monitor-configurator
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Values.clusterName }}
    app.kubernetes.io/component: monitor-configurator
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "chart.name" . }}
        app.kubernetes.io/instance: {{ .Values.clusterName }}
        app.kubernetes.io/component: monitor-configurator
    spec:
      restartPolicy: OnFailure
    {{- if .Values.monitor.serviceAccount }}
      serviceAccount: {{ .Values.monitor.serviceAccount }}
    {{- end }}
      containers:
      - name: tidb-dashboard-installer
        image: {{ .Values.monitor.dashboardInstaller.image }}
        args:
          - {{ .Values.clusterName }}-grafana:3000
        env:
          - name: GRAFANA_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.clusterName }}-monitor
                key: username
          - name: GRAFANA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.clusterName }}-monitor
                key: password
{{- end }}
