{{- if .Values.monitor.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tidb-cluster.grafana.fullname" . }}
  labels:
    app: {{ template "tidb-cluster.name" . }}
    component: monitor
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: {{ .Values.monitor.grafana.service.type }}
  selector:
    app: {{ template "tidb-cluster.name" . }}
    component: monitor
    release: {{ .Release.Name }}-{{ .Chart.Version }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tidb-cluster.prometheus.fullname" . }}
  labels:
    app: {{ template "tidb-cluster.name" . }}
    component: monitor
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  type: {{ .Values.monitor.prometheus.service.type }}
  selector:
    app: {{ template "tidb-cluster.name" . }}
    component: monitor
    release: {{ .Release.Name }}-{{ .Chart.Version }}
{{- end }}
