{{- if .Values.monitor.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.clusterName }}-monitor-configurator
  labels:
    app: {{ template "tidb-cluster.name" . }}
    component: monitor-configurator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "tidb-cluster.name" . }}
        component: monitor-configurator
        release: {{ .Release.Name }}-{{ .Chart.Version }}
    spec:
      restartPolicy: OnFailure
    {{- if .Values.rbac.create }}
      serviceAccount: {{ .Values.clusterName }}-monitor
    {{- end }}
      containers:
      - name: tidb-dashboard-installer
        image: {{ .Values.monitor.dashboardInstaller.image }}
        args:
          - {{ .Values.clusterName }}-grafana:3000
        env:
          - name: GRAFANA_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.clusterName }}-monitor
                key: username
          - name: GRAFANA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.clusterName }}-monitor
                key: password
{{- end }}
