{{- if .Values.binlog.pump.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterName }}-pump
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Values.clusterName }}
    app.kubernetes.io/component: pump
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
  pump-config: |-
{{ tuple "config/_pump-config.tpl" . | include "tidb-cluster.utils.template" | indent 4 }}
{{- end -}}
