apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: {{ template "cluster.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tidb-cluster
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  pvReclaimPolicy: {{ .Values.pvReclaimPolicy }}
  timezone: {{ .Values.timezone | default "UTC" }}
  services:
{{ toYaml .Values.services | indent 4 }}
  schedulerName: {{ .Values.schedulerName | default "default-scheduler" }}
  pd:
    replicas: {{ .Values.pd.replicas }}
    image: {{ .Values.pd.image }}
    imagePullPolicy: {{ .Values.pd.imagePullPolicy | default "IfNotPresent" }}
  {{- if .Values.pd.storageClassName }}
    storageClassName: {{ .Values.pd.storageClassName }}
  {{- end }}
  {{- if .Values.pd.resources }}
{{ toYaml .Values.pd.resources | indent 4 }}
  {{- end }}
  {{- if .Values.pd.nodeSelector }}
    nodeSelector:
{{ toYaml .Values.pd.nodeSelector | indent 6 }}
  {{- end }}
    nodeSelectorRequired: {{ .Values.nodeSelectorRequired | default true }}
  {{- if .Values.pd.tolerations }}
    tolerations:
{{ toYaml .Values.pd.tolerations | indent 4 }}
  {{- end }}
  tikv:
    replicas: {{ .Values.tikv.replicas }}
    image: {{ .Values.tikv.image }}
    imagePullPolicy: {{ .Values.tikv.imagePullPolicy | default "IfNotPresent" }}
  {{- if .Values.tikv.storageClassName }}
    storageClassName: {{ .Values.tikv.storageClassName }}
  {{- end }}
  {{- if .Values.tikv.resources }}
{{ toYaml .Values.tikv.resources | indent 4 }}
  {{- end }}
  {{- if .Values.tikv.nodeSelector }}
    nodeSelector:
{{ toYaml .Values.tikv.nodeSelector | indent 6 }}
  {{- end }}
    nodeSelectorRequired: {{ .Values.nodeSelectorRequired | default true }}
  {{- if .Values.tikv.tolerations }}
    tolerations:
{{ toYaml .Values.tikv.tolerations | indent 4 }}
  {{- end }}
  tikvPromGateway:
    image: {{ .Values.tikvPromGateway.image }}
    imagePullPolicy: {{ .Values.tikvPromGateway.imagePullPolicy | default "IfNotPresent" }}
  {{- if .Values.tikvPromGateway.resources }}
{{ toYaml .Values.tikvPromGateway.resources | indent 4 }}
  {{- end }}
  tidb:
    replicas: {{ .Values.tidb.replicas }}
    image: {{ .Values.tidb.image }}
    imagePullPolicy: {{ .Values.tidb.imagePullPolicy | default "IfNotPresent" }}
  {{- if .Values.tidb.resources }}
{{ toYaml .Values.tidb.resources | indent 4 }}
  {{- end }}
  {{- if .Values.tidb.nodeSelector }}
    nodeSelector:
{{ toYaml .Values.tidb.nodeSelector | indent 6 }}
  {{- end }}
    nodeSelectorRequired: {{ .Values.nodeSelectorRequired | default true }}
  {{- if .Values.tidb.tolerations }}
    tolerations:
{{ toYaml .Values.tidb.tolerations | indent 4 }}
  {{- end }}
    binlogEnabled: {{ .Values.binlog.pump.create | default false }}
    maxFailoverCount: {{ .Values.tidb.maxFailoverCount | default 3 }}
    separateSlowLog: {{ .Values.tidb.separateSlowLog | default false }}
    slowLogTailer:
      image: {{ .Values.tidb.slowLogTailer.image }}
      imagePullPolicy: {{ .Values.tidb.slowLogTailer.imagePullPolicy | default "IfNotPresent" }}
      {{- if .Values.tidb.slowLogTailer.resources }}
{{ toYaml .Values.tidb.slowLogTailer.resources | indent 6 }}
      {{- end }}
