apiVersion: v1
kind: ConfigMap
metadata:
{{- if .Values.enableConfigMapRollout }}
  name: {{ template "cluster.name" . }}-tidb-{{ template "tidb-configmap.data-digest" . }}
{{- else }}
  name: {{ template "cluster.name" . }}-tidb
{{- end }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tidb
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
{{ include "tidb-configmap.data" . | indent 2}}
