version: 2
updates:
- package-ecosystem: "gomod"
  directories:
  - "api/"
  - "tests/validation"
  - "/"
  schedule:
    interval: "daily"
  ignore:
  - dependency-name: "k8s.io/api"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  - dependency-name: "k8s.io/apiextensions-apiserver"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  - dependency-name: "k8s.io/apimachinery"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  - dependency-name: "k8s.io/cli-runtime"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  - dependency-name: "k8s.io/client-go"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  - dependency-name: "k8s.io/code-generator"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  - dependency-name: "k8s.io/component-base"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  - dependency-name: "k8s.io/kubectl"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  - dependency-name: "sigs.k8s.io/controller-tools"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  groups:
    k8s:
      patterns:
      - k8s.io/api
      - k8s.io/apiextensions-apiserver
      - k8s.io/apimachinery
      - k8s.io/cli-runtime
      - k8s.io/client-go
      - k8s.io/code-generator
      - k8s.io/component-base
      - k8s.io/kubectl
      - sigs.k8s.io/controller-runtime
      - sigs.k8s.io/controller-tools
      update-types:
      - patch
