# Default values for tikv-importer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# timezone is the default system timzone for TiDB
timezone: UTC

# clusterName is the TiDB cluster name, if not specified, the chart release name will be used
clusterName: demo

image: pingcap/tidb-lightning:v4.0.8
imagePullPolicy: IfNotPresent
# imagePullSecrets: []

# Whether enable the TLS connection between TiDB cluster components.
# If enabled, a Secret named "<clusterName>-importer-cluster-secret" must exist.
# To create this Secret: kubectl create secret generic <clusterName>-importer-cluster-secret --namespace=<namespace> --from-file=tls.crt=<path/to/tls.crt> --from-file=tls.key=<path/to/tls.key> --from-file=ca.crt=<path/to/ca.crt>
# tlsCluster:
#   enabled: true

storageClassName: local-storage
storage: 20Gi
resources:
  {}
  # limits:
  #   cpu: 16000m
  #   memory: 8Gi
  # requests:
  #   cpu: 16000m
  #   memory: 8Gi
affinity: {}
tolerations: []
pushgatewayImage: prom/pushgateway:v0.3.1
pushgatewayImagePullPolicy: IfNotPresent
config: |
  log-level = "info"
  [metric]
  job = "tikv-importer"
  interval = "15s"
  address = "localhost:9091"
