version: 2

jobs:
  build:
    docker:
      - image: andelf/doc-build:0.1.9
    working_directory: ~/pingcap/docs-tidb-operator

    steps:
      - checkout

      - run:
          name: "Special Check for Golang User - YOUR TAB SUCK"
          command: grep -RP '\t' *  | tee | grep '.md' && exit 1; echo ok

      - run:
          name: "Merge Makedown Files"
          command: cd en; python3 scripts/merge_by_toc.py; cd ../zh; python3 scripts/merge_by_toc.py;

      - run:
          name: "Generate PDF"
          command: cd ..; bash scripts/generate_pdf.sh;

      # echo "222.222.95.49 uc.qbox.me": adds a new host
      - deploy:
          name: "Publish PDF"
          command: |
            sudo bash -c 'echo "222.222.95.49 uc.qbox.me" >> /etc/hosts';
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              python3 scripts/upload.py output_en.pdf tidb-in-kubernetes-manual-en-dev.pdf;
              python3 scripts/upload.py output_zh.pdf tidb-in-kubernetes-manual-cn-dev.pdf;
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
