apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-controller-cr
  namespace: ${NAMESPACE}
  labels:
    app: admission-webhook
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get"]
- apiGroups: ["pingcap.com"]
  resources: ["tidbclusters"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-controller-sa
  namespace: ${NAMESPACE}
  labels:
    app: admission-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-controller-crb
  namespace: ${NAMESPACE}
  labels:
    app: admission-controller
subjects:
- kind: ServiceAccount
  name: admission-controller-sa
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-controller-cr
---
apiVersion: v1
kind: Service
metadata:
  name: admission-controller-svc
  namespace: ${NAMESPACE}
  labels:
    app: admission-controller
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: admission-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  namespace: ${NAMESPACE}
  labels:
    app: admission-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      serviceAccountName: admission-controller-sa
      containers:
        - name: admission-controller
          image: pingcap/tidb-operator:latest
          imagePullPolicy: Always
          command:
            - /usr/local/bin/tidb-admission-controller
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -v=2
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-controller-certs
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-admission-contorller-cfg
  labels:
    app: admission-controller
webhooks:
  - name: statefulset-admission-controller.pingcap.net
    failurePolicy: Fail
    clientConfig:
      service:
        name: admission-controller-svc
        namespace: ${NAMESPACE}
        path: "/statefulsets"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "UPDATE" ]
        apiGroups: [ "apps", "" ]
        apiVersions: ["v1"]
        resources: ["statefulsets"]
