apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tidb-lightning.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "tidb-lightning.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tidb-lightning
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  storageClassName: {{ .Values.dataSource.remote.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataSource.remote.storage }}
