apiVersion: v1
description: DEPRECATED(refer new instructions at https://docs.pingcap.com/tidb-in-kubernetes for tidb-operator v1.1 and above) - A Helm chart for TiDB Cluster
name: tidb-cluster
deprecated: true
version: v1-canary
home: https://github.com/pingcap/tidb-operator
sources:
  - https://github.com/pingcap/tidb-operator
keywords:
  - newsql
  - htap
  - database
  - mysql
  - raft
