apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: basic
spec:
  clusters:
  - name: basic
  prometheus:
    config:
      configMapRef:
        name: external-config
      commandOptions:
        - --web.read-timeout=5m
        - --web.max-connections=512
        - --storage.remote.read-concurrent-limit=10
    baseImage: prom/prometheus
<<<<<<< HEAD
    version: v2.11.1
=======
    version: v2.27.1
>>>>>>> 312df46f... Upgrade prometheus to v2.27.1 (#4222)
  grafana:
    baseImage: grafana/grafana
    version: 7.5.7
  initializer:
    baseImage: pingcap/tidb-monitor-initializer
    version: v5.2.0
  reloader:
    baseImage: pingcap/tidb-monitor-reloader
    version: v1.0.1
  imagePullPolicy: IfNotPresent
