{{- if and (eq .Values.admissionWebhook.enabled true) (eq .Values.admissionWebhook.certProvider "autoGenerator") }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ template "chart.name" . }}-admission-create
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component:  admission-cert-create
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
      name:  {{ template "chart.name" . }}-admission-create
    labels:
      app: {{ template "chart.name" . }}-admission-create
    serviceAccountName: tidb-admission-webhook-sa
    securityContext:
      runAsNonRoot: true
      runAsUser: 2000
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create
          image: {{ .Values.admissionWebhook.autoGenerator.certgen.image.repository }}:{{ .Values.admissionWebhook.autoGenerator.certgen.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          args:
            - create
            - --host=tidb-admission-webhook,tidb-admission-webhook.{{ $.Release.Namespace }},tidb-admission-webhook.{{ $.Release.Namespace }}.svc
            - --namespace={{ $.Release.Namespace }}
            - --secret-name=tidb-admission-webhook-certs
            - --key-name=key.pem
            - --cert-name=cert.pem
{{- end }}
