apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench
spec:
  template:
    spec:
      initContainers:
      - name: init
        image: sysbench
        command:
        - /bin/sh
        - -c
        - |-
          MYSQL_OPTS="-h${HOST} -P${PORT} -u${USER}"
          if [ -n "$PASSWORD" ]; then
            MYSQL_OPTS+=" -p${PASSWORD}"
          fi
          mysql $MYSQL_OPTS -Nse "create database if not exists ${DB};"
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              key: mysql-host
              name: sysbench-conf
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: mysql-port
              name: sysbench-conf
        - name: USER
          valueFrom:
            configMapKeyRef:
              key: mysql-user
              name: sysbench-conf
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              key: mysql-password
              name: sysbench-conf
              optional: true
        - name: DB
          valueFrom:
            configMapKeyRef:
              key: mysql-db
              name: sysbench-conf