{{- if and (eq .Values.admissionWebhook.enabled true) (eq .Values.admissionWebhook.certProvider "certManager") }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tidb-admission-webhook-crt
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component:  admission-cert-create
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  secretName: tidb-admission-webhook-certs
  commonName: tidb-admission-webhook
  dnsNames:
  - tidb-admission-webhook
  - tidb-admission-webhook.{{ $.Release.Namespace }}
  - tidb-admission-webhook.{{ $.Release.Namespace }}.svc
  issuerRef:
    name: tidb-selfsigning-issuer
    kind: ClusterIssuer
{{- end }}
