kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.clusterName }}-{{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backup
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.className }}
