{{- if eq .Values.mode "restore" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.clusterName }}-restore-{{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: restore
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
    {{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: restore
    spec:
      restartPolicy: OnFailure
      containers:
      - name: tidb-restore-job
        image: {{ .Values.image.backup }}
        command:
        - /bin/sh
        - -c
        - |-
{{ tuple "scripts/_start_restore.sh.tpl" . | include "helm-toolkit.utils.template" | indent 10 }}
        volumeMounts:
        - name: data
          mountPath: "/data"
      {{- if .Values.gcp }}
        - name: gcp-credentials
          mountPath: "/gcp"
          readOnly: true
      {{- end }}
        env:
        - name: BACKUP_NAME
          value: {{ .Values.name | quote }}
      {{- if .Values.gcp }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /gcp/credentials.json
      {{- end }}
      {{- if .Values.ceph }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.ceph.secretName }}
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.ceph.secretName }}
              key: secret_key
      {{- end }}
        - name: TIDB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: user
        - name: TIDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: password
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.name }}
    {{- if .Values.gcp }}
      - name: gcp-credentials
        secret:
          secretName: {{ .Values.gcp.secretName }}
    {{- end }}
{{- end }}
