apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: basic
  name: basic
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: prom/prometheus
  version: v2.11.0
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorSelector: {}
  externalLabels: 
    monitor: basic-tidb
  replicaExternalLabelName: replica
  replicas: 1
  resources:
    requests:
      memory: 25Gi
  ruleSelector:
    matchLabels:
      prometheus: basic
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      app: tidb
      cluster: basic
  retention: 168h
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: default
        resources:
          requests:
            storage: 100Gi
