---
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: demo1-backup-s3
  namespace: test1
  # annotations:
    # iam.amazonaws.com/role: "arn:aws:iam::123456789:role"
spec:
  # backupType: full
  # useKMS: false
  # serviceAccount: myServiceAccount
  br:
    cluster: myCluster
    # clusterNamespce: <backup-namespace>
    # logLevel: info
    # statusAddr: <status-addr>
    # concurrency: 4
    # rateLimit: 0
    # timeAgo: <time>
    # checksum: true
    # sendCredToTikv: true
  from:
    host: 172.30.6.56
    secretName: mySecret
    # port: 4000
    # user: root
    # tlsClientSecretName: <backup-tls-secretname>
  s3:
    provider: aws
    region: us-west-2
    bucket: backup
    prefix: test1-demo1
    # secretName: aws-secret
