---
apiVersion: pingcap.com/v1alpha1
kind: Restore
metadata:
  name: demo1-restore-s3-br
  namespace: test1
  # annotations:
    # iam.amazonaws.com/role: "arn:aws:iam::123456789:role"
spec:
  # backupType: full
  # useKMS: false
  # serviceAccount: myServiceAccount
  br:
    cluster: myCluster
    # clusterNamespce: <restore-namespace>
    # db: <db-name>
    # table: <table-name>
    # logLevel: info
    # statusAddr: <status-addr>
    # concurrency: 4
    # rateLimit: 0
    # timeAgo: <time>
    # checksum: true
    # sendCredToTikv: true
  to:
    host: 172.30.6.56
    secretName: mySecret
    # port: 4000
    # user: root
    # tlsClient:
    #   tlsSecret: <restore-tls-secretname>
  s3:
    provider: ceph
    endpoint: http://10.233.57.220
    secretName: ceph-secret
    bucket: backup
    prefix: test1-demo1
