---
apiVersion: pingcap.com/v1alpha1
kind: Restore
metadata:
  name: demo1-restore-s3-br
  namespace: test1
  # annotations:
    # iam.amazonaws.com/role: "arn:aws:iam::123456789:role"
spec:
  # backupType: full
  # serviceAccount: myServiceAccount
  br:
    cluster: myCluster
    # clusterNamespce: <restore-namespace>
    # enableTLSClient: true
    # db: <db-name>
    # table: <table-name>
    # logLevel: info
    # statusAddr: <status-addr>
    # concurrency: 4
    # rateLimit: 0
    # timeAgo: <time>
    # checksum: true
    # sendCredToTikv: true
  to:
    host: myHost
    secretName: mySecret
    # port: 4000
    # user: root
  s3:
    provider: aws
    region: myRegion
    bucket: backup
    prefix: test1-demo1
    # secretName: aws-secret
