name: auto-job-v2

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Add v2 label if target branch is feature/v2
        if: github.event.pull_request.base.ref == 'feature/v2'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'v2'

      - name: Add E2E trigger comment if target branch is feature/v2
        if: github.event.pull_request.base.ref == 'feature/v2'
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ github.token }}
          body: |
            /run-pull-e2e-kind-v2
