name: auto-job-v2

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Add v2 label if target branch is main or release-2.0
        if: github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'release-2.0'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'v2'
