name: Dependabot post updates
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write
jobs:
  post:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
      - uses: actions/checkout@v6
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'go_modules' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v6
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'go_modules' }}
        with:
          go-version-file: ./go.mod
          cache-dependency-path: "**/*.sum"
      - name: go build
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'go_modules' }}
        run: |
          make tidy
          make generate
          make build
      - name: git update
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'go_modules' }}
        uses: planetscale/ghcommit-action@v0.2.19
        with:
          commit_message: "post update after go dependencies updation"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: close and reopen to retrigger workflow
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'go_modules' }}
        run: |
          gh pr ready --undo ${{ github.event.pull_request.number }}
          gh pr comment ${{ github.event.pull_request.number }} -b "/ok-to-test"
          gh pr comment ${{ github.event.pull_request.number }} -b "/test ready-for-review"
        env:
          GITHUB_TOKEN: ${{ github.token }}
