name: PR Trigger Website-docs Building 

on:
  push:
    branches:
      - master
      - release-4.0
      - release-3.1
      - release-3.0
      - release-2.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.1.1
      with:
          token: ${{ secrets.PR_TRIGGER_BUILD_TOKEN }}
          repository: /Ti-FE/website-docs
          event-type: triggered
          client-payload: '{"repo": "${{ github.repo }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'