apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-disk
parameters:
  type: available
provisioner: alicloud/disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
